[general]
name = "sudoku"
version = "0.1.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
output = "sudoku.out"
opt_level = "basic"
files = [
    "sudoku.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
# path = "../../fixlang-minilib-app"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-xml"
version = "*"
# path = "../../fixlang-minilib-xml"
git = { url = "https://github.com/pt9999/fixlang-minilib-xml.git" }

[[dependencies]]
name = "minilib-media"
version = "*"
# path = "../../fixlang-minilib-media"
git = { url = "https://github.com/pt9999/fixlang-minilib-media.git" }

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }

[[dependencies]]
name = "random"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "time"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }

[[dependencies]]
name = "minilib-random"
version = "0.1.2"
git = { url = "https://github.com/pt9999/fixlang-minilib-random.git" }